### ISSUE TITLE
Missing some dependencies

### ISSUE THREAD

**Issue by EvgAnis** [Vicky-cmd/Authentication-Service#1]
Could you please provide these two dependencies to be able to build the project:
1:
```
<dependency>
			<groupId>com.infotrends.in.InfoTrendsIn</groupId>
			<artifactId>ExceptionDependencies</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-web</artifactId>
				</exclusion>
			</exclusions>
</dependency>

```
2: 
```
<dependency>
			<groupId>com.infotrends.in.InfoTrendsIn</groupId>
			<artifactId>SecondaryDependencies</artifactId>
			<version>0.0.1-SNAPSHOT</version>
</dependency>
```
SecurityConstants and BusinessException are unabailable

**Comment by LeonardoMendoncaDev** [comment]
Hi, are the dependencies already available?

**Comment by akshaymemane** [comment]
Yes, the dependencies are missing.
Would be a great help if you provide those.
@Vicky-cmd

**Comment by Oudalally** [comment]
It is extremely unlikely that these will be provided.
It is also extremely unlikely that the code will be updated to do away with the deprecated classes.

At the VERY least, a warning on the front page showing that this project cannot be built would save those of us who are using this style of example project as a learning tool a lot of wasted time.
